# ifndef MAIN_H
# define MAIN_H
int add(int, int);
void print_to_98(int);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(int);
int _isalpha(int);
int print_sign(int);
int _abs(int);
int print_last_digit(int);
void jack_bauer(void);
void times_table(void);
int _isupper(int);
int _isdigit(int); 
int mul(int, int); 
void print_numbers(void); 
void print_most_numbers(void);
void more_numbers(void);
void print_line(int);
void print_diagonal(int);
void print_square(int);
void _start(void);
void print_triangle(int); 
int _putchar(char);
void reset_to_98(int);
void swap_int(int, int);
int _strlen(char *);
void _puts(char *);
void print_rev(char *);
void rev_string(char *);
void puts2(char *);
void puts_half(char *);
void print_array(int *, int);
char *_strcpy(char *, char *);
char *_strcat(char *, char *);
char *_strncat(char *, char*, int);
char *_strncpy(char *, char*, int);
int _strcmp(char *, char *);
void reverse_array(int *,int);
char *string_toupper(char *);
char *cap_string(char *);
char *leet(char *);
unsigned int _strlenA(char *);
char *_memset(char *, char, unsigned int);
char *_memcpy(char *, char *, unsigned int);
char *_strchr(char *, char);
void pointnull(char **);
unsigned int _strspn(char *, char *);
char *_strpbrk(char *, char *);
char *_strstr(char *, char *);
void print_chessboard(char (*a)[8]);
void print_diagsums(int *a, int size);
# endif
